# Generated by Django 6.1 on 2026-08-14 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('vehicles', '0001_initial'),
        ('work_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake_reason', models.CharField(max_length=300)),
                ('initial_observation', models.CharField(max_length=300)),
                ('estimate_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='customers.customer')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='work_orders.workorderstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Work_Order',
                'verbose_name_plural': 'Work_Orders',
                'db_table': 'WorkOrder',
            },
        ),
    ]
