# Generated by Django 6.1 on 2026-08-15 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0002_workorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('new_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_status_history', to='work_orders.workorderstatus')),
                ('previous_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='previous_status_history', to='work_orders.workorderstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_order_status_history', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_order_status_history', to='work_orders.workorder')),
            ],
            options={
                'verbose_name': 'Work_Order_Status_History',
                'verbose_name_plural': 'Work_Order_Status_History',
                'db_table': 'WorkOrderStatusHistory',
            },
        ),
    ]
