# Generated by Django 6.1 on 2026-08-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0003_workorderstatushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderstatushistory',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
